### ISSUE TITLE
can't get  past  nagscreen

### ISSUE THREAD

**Issue by yohimbe110** [SmartPack/PackageManager#1]
I can see the menu below the warning overlay but I can't close it.

**Comment by sunilpaulmathew** [comment]
> I can see the menu below the warning overlay but I can't close it.

Thanks for reporting.
However, ai don't understand the issue clearly.
Can I have a screenshot, please?

**Comment by yohimbe110** [comment]
#
![Screenshot_20200301-084155_Package_Manager](https://user-images.githubusercontent.com/22657539/75621773-1776b180-5b99-11ea-8ee8-5c87fd25ae59.png)

**Comment by sunilpaulmathew** [comment]
@yohimbe110 
Ahh, I got it...
So, your device secren is too small?
Also, you can't scrol?
I'll look for it anyway...

**Comment by yohimbe110** [comment]
yes you're right installed it on my Google Pixel tab
![IMG_20200301_090722](https://user-images.githubusercontent.com/22657539/75622031-20b54d80-5b9c-11ea-8711-af6f49edfdc2.jpg)
