### ISSUE TITLE
Keyboard displays enter button when searching

### ISSUE THREAD

**Issue by ZenerDeveloper** [SmartPack/PackageManager#17]
When using the search bar, the keyboard displays the enter key, meaning if you hit that instinctivly from other apps with a search bar, it adds a newline to the searchbox. I don't think it is possible to have a newline in a package name, and having a search button that hides the keyboard would make more sense.

**Comment by sunilpaulmathew** [comment]
> When using the search bar, the keyboard displays the enter key, meaning if you hit that instinctivly from other apps with a search bar, it adds a newline to the searchbox. I don't think it is possible to have a newline in a package name, and having a search button that hides the keyboard would make more sense.

You're right. & I'll look on that issue. Thanks again for constantly supporting my work.

**Comment by ZenerDeveloper** [comment]
Of course, this is one of theost used apps on my phone, as I have been removing tons of bloat. Thanks for creating such a useful program!
