### ISSUE TITLE
add functions Select all

### ISSUE THREAD

**Issue by Pantyhose-X** [SmartPack/PackageManager#22]

**Comment by sunilpaulmathew** [comment]
@Pantyhose-X 
Should be available on the next update. So, closing this issue.

**Comment by Pantyhose-X** [comment]
hi @sunilpaulmathew 
Batch Options  Select all functions
![Screenshot_20210717-083601](https://user-images.githubusercontent.com/42504385/126020719-1106e97c-1203-4285-b7c9-03f7fa4ac18f.jpg)

**Comment by sunilpaulmathew** [comment]
> hi @sunilpaulmathew
> Batch Options Select all functions
> ![Screenshot_20210717-083601](https://user-images.githubusercontent.com/42504385/126020719-1106e97c-1203-4285-b7c9-03f7fa4ac18f.jpg)

Have you checked the button next to the "Search" menu?

**Comment by Pantyhose-X** [comment]
> > hi @sunilpaulmathew
> > Batch Options Select all functions
> > ![Screenshot_20210717-083601](https://user-images.githubusercontent.com/42504385/126020719-1106e97c-1203-4285-b7c9-03f7fa4ac18f.jpg)
> 
> Have you checked the button next to the "Search" menu?

Checked no button
Android 8.0

**Comment by sunilpaulmathew** [comment]
@Pantyhose-X 
On v4.8. Btw, I'm moving that switch to the "Batch Options" card on bottom on next version.
![Screenshot_20210719-073211](https://user-images.githubusercontent.com/15515387/126107923-4740845b-3585-447d-a403-0087bc08f64d.jpg)

**Comment by Pantyhose-X** [comment]
> @Pantyhose-X
> On v4.8. Btw, I'm moving that switch to the "Batch Options" card on bottom on next version.
> ![Screenshot_20210719-073211](https://user-images.githubusercontent.com/15515387/126107923-4740845b-3585-447d-a403-0087bc08f64d.jpg)

![2](https://user-images.githubusercontent.com/42504385/126246909-515038de-665c-442d-b4ea-f87aa95d0984.jpg)
![1](https://user-images.githubusercontent.com/42504385/126246916-decfd57c-7df8-4518-bb52-9ebd7e9fcd26.jpg)
no button

**Comment by sunilpaulmathew** [comment]
@Pantyhose-X 
Because you're clicking the ഇരോൺ button :)
![Screenshot_20210720-072545](https://user-images.githubusercontent.com/15515387/126266560-7c32e12b-c5b6-4007-a313-ccc09069f7aa.jpg)

**Comment by Pantyhose-X** [comment]
> @Pantyhose-X
> Because you're clicking the wrong button :)
> ![Screenshot_20210720-072545](https://user-images.githubusercontent.com/15515387/126266560-7c32e12b-c5b6-4007-a313-ccc09069f7aa.jpg)

l click the button and nothing happens
