### ISSUE TITLE
Search converts all characters to lowercase

### ISSUE THREAD

**Issue by ZenerDeveloper** [SmartPack/PackageManager#24]
When you search, the matching section (Name or Package) gets converted to lowercase.
Example:
Name: `Smart Switch Agent`
Package: `com.sec.android.easyMover.Agent`
If you search a word in the title say `smart` it becomes
Name: `smart switch agent`
Package: `com.sec.android.easyMover.Agent`
When tapped it works fine however if you search `samsung` it becomes
Name: `Smart Switch Agent`
Package: `com.sec.android.easymover.agent`
Which if tapped says the package was just removed.
If you need to test just ceeate a dummy app eith capitals in the title and package name.

**Comment by sunilpaulmathew** [comment]
I'm closing this issue since it is already addressed in a recent update. Feel free to reopen this issue if you're not satisfied.
