### ISSUE TITLE
[Feature] batch uninstall

### ISSUE THREAD

**Issue by Efreak** [SmartPack/PackageManager#26]
It would be nice to have an option to batch uninstall apps. I've got an app that does this, but that's *all* it does and I'm trying to clean up the number of extra apps I've got installed.
- Basically just send a group of installation requests all at once to ease uninstalling plugins like Tachiyomi extensions or keyboard languages.
- A better implementation would only send two requests at a time, and wait until an app has been uninstalled to send another request (if it's still possible receive these broadcasts; if not, you could also check the list of installed packages on a timer).
  - Having two requests would be helpful, as even on Samsung Galaxy Tab S6 (2019 device) Android doesn't respond immediately to install/uninstall requests (usually from fdroid, but also from Tachiyomi and file explorer).
  - At the same time, only having two requests open would make it easier to pause the batch operation by only making the request if the app is in the foreground (ie, if I switch to another app, stop processing), and then continue again when I switch back to the Package Manager app.

**Comment by sunilpaulmathew** [comment]
@Efreak 
I don't know it is really possible without root access. However, I would like to have a look at this issue, especially, the second point you mentioned. Btw, sorry for the slight delay in my reply.

**Comment by Efreak** [comment]
>  I don't know it is really possible without root access

There's an open source app called [Batch Uninstaller](https://github.com/sarbajitsaha/Batch-Uninstaller) that does the most basic of what I'm requesting, if that helps. Implementing that *should* be trivial, I think, though it would be nice to be able to interrupt it, as mentioned.


> Btw, sorry for the slight delay in my reply.

You don't owe me anything, and I'm happy you're even considering my requests :+1:

**Comment by sunilpaulmathew** [comment]
@Efreak 
So, I managed to do it. If you like to have a look on it, please try this [APK](https://www.dropbox.com/s/rvi05lbi7yeya2i/com.smartpack.packagemanager.apk?dl=0). Thanks
**Limitation**: The user needs to approve each uninstallation event.

**Comment by sunilpaulmathew** [comment]
I'm closing this issue since it is already addressed in v4.9. Feel free to reopen this issue if you're not satisfied.
