### ISSUE TITLE
[Enhancement] app name at top of app view

### ISSUE THREAD

**Issue by Efreak** [SmartPack/PackageManager#28]
Currently in the single app view, the name/icon of the current app is only shown in the App Info tab. Please show it above the tab bar on the other tabs as well, or at the bottom; if I've switched out of the app to look at data from another app, it would be nice to be able to see which app I'm looking at directly from the recent view, without having to open the app and switch back to the app info tab.

**Comment by sunilpaulmathew** [comment]
@Efreak 
I'll do it, unless it makes some serious UI samage.

**Comment by sunilpaulmathew** [comment]
I'm closing this issue since it is already addressed in a recent update. Feel free to reopen this issue if you're not satisfied.
