### ISSUE TITLE
Translatable "share" string should not be shared between header and a button

### ISSUE THREAD

**Issue by Aga-C** [SmartPack/PackageManager#30]
Hi,

I've noticed that in the app you're reusing the translatable string "share" between the header of the dialog and an action button (check screenshot below). It sounds good in English, but it's not the case in other languages.

![obraz](https://user-images.githubusercontent.com/85929121/127544990-57ce0eea-747c-4aa1-8397-4dbcbe9421ef.png)

In this case, the wrong text in the header "Udostępnij [something]?" could be translated back to English as "Would you share [something]?". Properly it should be "Udostępnić [something]?" while action button should still be "Udostępnij".

In my opinion the best way to approach this would be to create a separate string with a formatter placeholder, something like "Share %s?". This will be also more proof for other languages that can use other order of words.

Thanks!

**Comment by sunilpaulmathew** [comment]
@Aga-C 
Fully agree with your comment. I'll look for a solution as you suggested, although it will make headaches for translators. Thank you.

**Comment by Aga-C** [comment]
@sunilpaulmathew I've seen your commit and I think you've changed other text than I mentioned 😅 I meant to separate the header title to not share the same string with a button.
![image](https://user-images.githubusercontent.com/85929121/127613341-7cfa2ba5-1908-4855-af98-0705ae5e7440.png)

However, the change is good, because now that message can also be better translated 👍

Thanks!

**Comment by sunilpaulmathew** [comment]
@Aga-C 
Infact, I forgot to update the title. I'm planning to simply show the exported app name there, so that it will be like the attached image. Thanks again.
![Screenshot_20210730-101209](https://user-images.githubusercontent.com/15515387/127622955-8349cc8c-4bea-44fc-b155-578c34754c8a.jpg)

**Comment by Aga-C** [comment]
Hi. Can you add the new string `export_apk_summary` to POEditor?

**Comment by sunilpaulmathew** [comment]
> Hi. Can you add the new string `export_apk_summary` to POEditor?

Sure, will be done this evening or tomorrow. No access to computer now. Thank You

**Comment by sunilpaulmathew** [comment]
> Hi. Can you add the new string `export_apk_summary` to POEditor?

It is done!
