### ISSUE TITLE
Improve Uninstall: support restoring system apps to factory versions

### ISSUE THREAD

**Issue by jaswinder77** [SmartPack/PackageManager#38]

**Comment by jaswinder77** [comment]
Support for uninstalling *updates* of system apps should be possible without adb as well even though adb command would be needed to uninstall system app itself. It may not be possible in some cases that I am not aware of but at least on my device Moto G8 Power Lite (Android 10), I have already tried several apps which can easily uninstall updates of system apps even though the "App Info" screen of system apps does not show an "Uninstall" button.

Links to some of such apps:

[App Manager - Apps on Google Play](https://play.google.com/store/apps/details?id=com.lb.app_manager)

[App Manager - Android package manager](https://f-droid.org/packages/io.github.muntashirakon.AppManager)

[Smart App Manager](https://play.google.com/store/apps/details?id=com.james.SmartUninstaller)

[ML Manager: APK Extractor](https://play.google.com/store/apps/details?id=com.javiersantos.mlmanager)

**Comment by sunilpaulmathew** [comment]
> Support for uninstalling _updates_ of system apps should be possible without adb. At least on my device Moto G8 Power Lite (Android 10), I have already tried several apps which can easily uninstall updates of system apps even though the "App Info" screen of system apps does not show an "Uninstall" button.
> 
> Links to some of such apps:
> 
> [App Manager - Apps on Google Play](https://play.google.com/store/apps/details?id=com.lb.app_manager)
> 
> [App Manager - Android package manager](https://f-droid.org/packages/io.github.muntashirakon.AppManager)
> 
> [Smart App Manager](https://play.google.com/store/apps/details?id=com.james.SmartUninstaller)
> 
> [ML Manager: APK Extractor](https://play.google.com/store/apps/details?id=com.javiersantos.mlmanager)

Re-opening this issue. I'll address this in the next update.
