### ISSUE TITLE
UI related to "Batch Options" can be improved

### ISSUE THREAD

**Issue by jaswinder77** [SmartPack/PackageManager#39]
A checkbox beside the  "Batch Options" (as it currently exists) may create confusion rather than help users.

Rather than clicking on "Batch Options" most users are likely to click on checkbox  without any intention to select all the apps, and would most likely mistake "Batch Options" as just a label to the checkbox rather than a menu of more commands.

Rather than a checkbox there, what could be more user-friendly is an ellipsis at the end (like this: "Batch Options…") to signal that more commands are available on clicking it. With this little change many unintended clicks on "select all" checkbox will be avoided.

And the "select all" checkbox could be placed at the top right on the existing toolbar.

![IMG_20210830_162025.png](https://user-images.githubusercontent.com/31370528/131779209-4f8b6abd-d899-46e2-8689-3fe28c235552.png)

OR

It could be as we see in [File Manager +](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager)  (see screenshot below) where the "select all" button is at the top right along with a "select range" button (maybe, we do not need it). At the top left, there is a label which displays _selected items/total no. of items_ along with a Cancel [X] button. And a bottom toolbar displays icons for different batch commands.

![Screenshot_20210902-015632.png](https://user-images.githubusercontent.com/31370528/131743170-c78400f9-c55a-42da-b923-dc44d1725ad1.png)

OR

It could be as we see in [Clipto](https://play.google.com/store/apps/details?id=com.wb.clipboard.pro) where a bottom toolbar appears with "select all" and cancel (x) buttons on left, and batch commands on the right.

![Screenshot_20210830-152101.png](https://user-images.githubusercontent.com/31370528/131744111-55aa892c-3084-4d7b-b67d-4f8f24fc6866.png)

OR

As we have in [Safe Uninstaller](https://play.google.com/store/apps/details?id=uninstall.apps.uninstall.free)
![Screenshot_20210902-023447.png](https://user-images.githubusercontent.com/31370528/131745069-2b33fe4d-8e91-446a-91a0-941016b91c4b.png)

![Screenshot_20210902-023102.png](https://user-images.githubusercontent.com/31370528/131745130-aded212b-8b7d-41ef-8632-d72a550c3a6a.png)

![Screenshot_20210902-023234.png](https://user-images.githubusercontent.com/31370528/131745185-d95df2fb-b500-48e6-9fcc-cb8b470a0451.png)

OR

As we have in [Easy Uninstaller](https://play.google.com/store/apps/details?id=mobi.infolife.uninstaller)
![Screenshot_20210902-001827.png](https://user-images.githubusercontent.com/31370528/131745560-8571894e-0a57-42ef-a523-fe8ec653132e.png)

OR

As we have in ["1Tap Cleaner"](https://play.google.com/store/apps/details?id=com.a0soft.gphone.acc.free)
![Screenshot_20210830-150342.png](https://user-images.githubusercontent.com/31370528/131746253-6e73797d-e152-40e9-bae3-d60c7ca73679.png)

OR

it could be a combination of ideas derived from all the screenshots above.

**Comment by Valdnet** [comment]
The current function looks a bit strange 😉.

**Comment by sunilpaulmathew** [comment]
@jaswinder77  @Valdnet 
What about replacing the check box with an additional menu "Select All" on clicking the "Batch Options" button?

**Comment by sunilpaulmathew** [comment]
@jaswinder77  @Valdnet 
Okay, what do you think about placing a "**Select All**" menu (please see screenshot attached below) in the **Batch Options** card, instead of the misleading checkbox we presently have?

![Screenshot_1631116206](https://user-images.githubusercontent.com/15515387/132543931-ac6cc42d-a881-47e6-bc06-f44e74d5013d.png)

**Comment by Valdnet** [comment]
In my opinion it is good. It looks better right away 👍.

**Comment by sunilpaulmathew** [comment]
So, this will be addressed in v5.2. So, closing this issue. Feel free to reopen if you guys are not satisfied with it. Thanks.
