### ISSUE TITLE
Unable to select an installation file

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#40]
Steps:

1. Select "Install Split APKs".
2. Select the directory with the installers in XAPK format.

When you try to install an XAPK installation package, you do not see the XAPK formatted installers in the in-built file picker.

Apps:
Android 10
Package Manager v5.1

**Comment by sunilpaulmathew** [comment]
@Valdnet 
I am convinced that supporting different file manager apps are literally impossible. That's why implemented our own file picker for ap. Can you please try with the in-built file picker of the app? There is an option on the Settings page to enable it.
Alternately, try a supporter (tested by me) file manager app, like Material Files (still, a lesser efficient than in-built file picker).
Can you tell me after trying? Thanks.

**Comment by Valdnet** [comment]
> Can you please try with the in-built file picker of the app?

@sunilpaulmathew Attempting to install XAPK was made with the built-in file selector.

> There is an option on the Settings page to enable it.

Yes. It's on.

**Comment by sunilpaulmathew** [comment]
> > Can you please try with the in-built file picker of the app?
> 
> @sunilpaulmathew Attempting to install XAPK was made with the built-in file picker.
> 
> > There is an option on the Settings page to enable it.
> 
> Yes. It's on.

Sorry for misunderstand the first comment.
In that case, there are something seriously wrong somewhere? Just for the clarification, are you sure that the file is really "xapk"? Also, I doubt the issue will affect other formats (apkm & apks) as well. It will be great if you could try some of them and update the results.

**Comment by Valdnet** [comment]
> Just for the clarification, are you sure that the file is really "xapk"?

Yes, I'm sure the installers in XAPK format are in the given directory.

Screenshot from the built-in file picker:
![obraz](https://user-images.githubusercontent.com/47037905/132342393-58c9fdc1-a7aa-4f6a-a82e-fdd78a36b8d3.png)
Screenshot from another application:
![obraz](https://user-images.githubusercontent.com/47037905/132342203-b6c51bc5-6656-44f0-a270-17caf7bb8c39.png)

**Comment by Valdnet** [comment]
@sunilpaulmathew I will add that I have another XAPK installer installed. Maybe this something will help you solve the problem.

**Comment by sunilpaulmathew** [comment]
> that I have another XAPK installer installed

Which one? Is that working? If it is also opensource, it will be helpful. Btw, out of curiosity, have you tried with the device file manager (material files etc) after disabling the switch mentioned in my first comment?

**Comment by Valdnet** [comment]
> Which one? Is that working?

This is the "XAPK Installer" application.

> Btw, out of curiosity, have you tried with the device file manager (material files etc) after disabling the switch mentioned in my first comment?

Yes. I tried. The XAPK file is seen, but "Package Manager" cannot be selected as the application to install.

**Comment by Valdnet** [comment]
After selecting by another file manager, I get the message: `Please select a file with .apk / .aks / .apkm / .xapk / .extension.`

**Comment by sunilpaulmathew** [comment]
> After selecting by another file manager, I get the message: `Please select a file with .apk/ .aks/ .apkm/ .xapk extension.`

should be because, my app failed to get proper file path from the external file manager.

**Comment by Valdnet** [comment]
@sunilpaulmathew I found the cause of the issue.

If an installation file contains a space in its name, the in-built file picker does not see it e.g: `file name.xapk`.
This was confusing to XAPK because these files had a space in their name.
Generally, all files with a space in their name are not visible to the in-built file picker.

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew I found the cause of the issue.
> 
> If an installation file contains a space in its name, the in-built file picker does not see it e.g: `file name.xapk` or `file name.apk`.
> This was confusing to XAPK because these files had a space in their name.
> Generally, all files with a space in their name are not visible to the in-built file picker.

That was a great input. Honesty, I do not even think about that situation while coding the file picker. Let me think how to manage it.
Big Thanks

**Comment by sunilpaulmathew** [comment]
@Valdnet 
This issue is fixed with v5.2. Please feel free to re-open it if you still find issues. Thanks.
