### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#42]
In the search window that appears, the text "Search" and a flashing "pipe" appear, overlapping each other. It does not look aesthetically pleasing.

![obraz](https://user-images.githubusercontent.com/47037905/132462436-60b8c814-5bfb-434f-a627-705918455b16.png)

The text string should be gray and at the beginning of the search window and the "pipe" sign should appear at the beginning of the search window in front of the text string.

Example:

![obraz](https://user-images.githubusercontent.com/47037905/132465391-be8ff2e0-536e-49d8-b2b8-71df04c31229.png)

Apps:
Android 10
Package Manager v5.1

**Comment by sunilpaulmathew** [comment]
@Valdnet Probably, you will like this too?
![Screenshot_1631123114](https://user-images.githubusercontent.com/15515387/132558776-0e54af5b-a009-4452-8138-d5659c48617b.png)

**Comment by Valdnet** [comment]
> Probably, you will like this too?

Of course 👍.
