### ISSUE TITLE
Setting default directory

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#47]
A request to add a new function in the application settings that could select and set the default directory for in-built file picker.

Justification:
We often keep the installation files in one directory with subdirectories, to which constant selection is laborious and inconvenient for the user.

**Comment by sunilpaulmathew** [comment]
@Valdnet This is done, but in a different style. App will now remember the last directory and reopen directly when you re-launch File Picker.  Closing this issue now. But, please reopen if you're not satisfied.
