### ISSUE TITLE
Directory icons background for a light theme 

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#49]
The background of the directory icons in the in-built file picker for a light theme has a dark background. They are probably from the dark theme.

![obraz](https://user-images.githubusercontent.com/47037905/132846719-178ca907-6de6-44d7-a6dc-4229883c8981.png)

Apps:
Android 10
Package Manager v5.2

**Comment by Valdnet** [comment]
After making this change in commit xxx got even more interesting 😁.
For users who rarely use the system arrow at the bottom of their smartphone, they may be a bit surprised that they can't go back or enter the main directory.
I suggest adding a directory path at the top of the application so that you can select a directory from the given path.

Something like that:

![obraz](https://user-images.githubusercontent.com/47037905/132850028-1aa2d580-935d-426d-9877-1b2ec8bdec2a.png)

**Comment by sunilpaulmathew** [comment]
> The background of the directory icons in the in-built file picker for a light theme has a dark background. They are probably from the dark theme.
> 
> ![obraz](https://user-images.githubusercontent.com/47037905/132846719-178ca907-6de6-44d7-a6dc-4229883c8981.png)
> 
> Apps:
> Android 10
> Package Manager v5.2

Not really. I actually [hardcoded](https://github.com/SmartPack/PackageManager/blob/7b0bbc712adf734f0c0ef97db9d3d8547cdffa64/app/src/main/res/drawable/ic_background_circle.xml#L6) black background. Otherwise, I feel it look weird by considering the huge transparent area inside the folder icon.

**Comment by Valdnet** [comment]
Or maybe a gray background? Or something more unobtrusive. Overall, it looks a bit unsightly 😉.

**Comment by sunilpaulmathew** [comment]
> Or maybe a gray background? Or something more unobtrusive. Overall, it looks a bit unsightly 😉.

Thanks for the idea. I'll surely have a look on that possibility.

**Comment by sunilpaulmathew** [comment]
> Or maybe a gray background? Or something more unobtrusive. Overall, it looks a bit unsightly 😉.

What about this color in light mode?
![Screenshot_1631308361](https://user-images.githubusercontent.com/15515387/132918296-a3e461c7-9a56-429e-9b6f-23ca56e51ce6.png)

**Comment by Valdnet** [comment]
However, I suggest changing to a white background.
Example:

![obraz](https://user-images.githubusercontent.com/47037905/132945045-476369bd-216f-46ba-bfeb-7eadac9eaad7.png)
