### ISSUE TITLE
Issue with package manager

### ISSUE THREAD

**Issue by jester3699** [SmartPack/PackageManager#5]
Good day! I followed a link from your kernal manager which I have been using for a while on a sm-t910t (samsung galaxy note 4 on tmo.) Decided to try out the package manager as a modern replacement for the waaaaay out dated ROM toolbox that I have been holding at the last useful version for years now. The only thing I am after is freezing and restoring apps so this seemed perfect. The package manager installed fine and listed some of the installed apps for a moment then when I tapped the settings icon they all disappeared and will not return even after a reboot. Is this something I am doing wrong or an app issue maybe? Currently running the final version of aicp14 (android 9) which is rooted old school with SuperSU + suhide which is all working correctly as far as I am aware (root works and the work app I am hiding it from doesn't see it.) Any direction would be great, thank you!

**Comment by sunilpaulmathew** [comment]
I have no idea about what is happening on your device. However, I suspect that it should be something that beyond the scope of the app.

**Comment by jester3699** [comment]
This is what is happening. Sorry, realized I had forgotten to attach this
pic. Thanks for your time :-)
