### ISSUE TITLE
Application shutdown setting

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#53]
I propose to add a setting in the application options for enabling or disabling confirmation when disabling the application. If you decide to receive a confirmation message that the application is disabled, you should add the option to disable it in the application settings, so that the user can decide for himself how the application is closed. Whether with or without confirmation. Sometimes double-clicking on an arrow is annoying for the user.

It's about this message:

![obraz](https://user-images.githubusercontent.com/47037905/133157486-4322dd1d-eaca-4926-b23e-abc3538f58bb.png)

**Comment by Valdnet** [comment]
@sunilpaulmathew In the trial version, the added function of changing the shutdown works correctly 👍. Eventually, users will get rid of repeated clicking 😉.

**Comment by sunilpaulmathew** [comment]
@Valdnet 
Closing this issue since it is already addressed.
