### ISSUE TITLE
Settings visual improvements

### ISSUE THREAD

**Issue by Aga-C** [SmartPack/PackageManager#54]
Hi,

In the test build, the sections names should look a bit different from the settings. I think that now with section names, it would look better if you'd:
- use smaller font for the section names, and maybe they could have another color
- remove the horizontal lines between the settings, and between a section name and the first setting (I would only leave a line after the last setting in a section)

In the screenshot below, I've marked which lines I'd remove and what should be written with a smaller font.
![image](https://user-images.githubusercontent.com/85929121/133162542-754bf4b9-f6f3-4e83-8c8e-4f118bf7b65a.png)

Also, there is a bug: an icon for Documentation is invisible in the light theme.
![image](https://user-images.githubusercontent.com/85929121/133162857-a3783da3-9d4f-468f-b437-73556e590fe2.png)

**Comment by sunilpaulmathew** [comment]
@Aga-C That is a great suggestion I really like to work on.

**Comment by Valdnet** [comment]
@Aga-C Very good suggestions 👍.

@sunilpaulmathew I would also fix the icon for "Translation" because its color is inappropriate for a dark theme. It stands out too much. I would stick to the color of the themes. And for a light theme, the icon is half obscured by a black background.

**Comment by sunilpaulmathew** [comment]
> @Aga-C Very good suggestions 👍.
> 
> @sunilpaulmathew I would also fix the icon for "Translation" because its color is inappropriate for a dark theme. It stands out too much. I would stick to the color of the themes. And for a light theme, the icon is half obscured by a black background.

In fact, I leave it as such with an aim to get more attention from users. Also, it need some work to make it black/white as the respective drawable for that specific icon is different (got from an external website while others are from android studio).

**Comment by Valdnet** [comment]
> In fact, I leave it as such with an aim to get more attention from users.

But that doesn't fit in with the whole thing.

The icon needs to be processed anyway, because for a light theme it is obscured by a black background.

I suggest replacing this icon with an icon from the icon gallery that will match the given option. After all, it doesn't have to be an icon for the translation page. I would even suggest changing it 😉.

**Comment by sunilpaulmathew** [comment]
>  After all, it doesn't have to be an icon for the translation page.

Of course, but they are so kind to opensource community. Provided free translation for almost all of my application. Anyway, I'll look for an alternate solution.

**Comment by Valdnet** [comment]
It is certainly enough that you mention them in the text string 😉.

**Comment by sunilpaulmathew** [comment]
I think this is good enough for now?
![Screenshot_1631648263](https://user-images.githubusercontent.com/15515387/133322697-f4a97b43-0c44-4573-ae92-55bfb5ab5c5a.png)

**Comment by Aga-C** [comment]
Looks good 👍

**Comment by sunilpaulmathew** [comment]
> Looks good 👍 Maybe there could be just a bit larger margin between the app title and the first section name.

Done. Btw, any comments on this? Probably a better description.
![Screenshot_1631651328](https://user-images.githubusercontent.com/15515387/133329219-56a64ef4-0586-44bd-8758-3da51a87b067.png)

**Comment by Aga-C** [comment]
For me, it's ok.

@Valdnet  What do you think?

**Comment by sunilpaulmathew** [comment]
> For me, it's ok.
> 
> @Valdnet What do you think?

@Valdnet 
Btw, this one too...
![Screenshot_1631652863](https://user-images.githubusercontent.com/15515387/133332512-99e1c41b-e6c2-4900-973e-3455f59a4516.png)

**Comment by sunilpaulmathew** [comment]
@Valdnet @Aga-C 
[Here](https://www.dropbox.com/s/rvi05lbi7yeya2i/com.smartpack.packagemanager.apk?dl=0) is a test build when you have time. I guess almost everything is addressed (at least in an initial form). I shall upload the strings into POEditor after receiving your initial comments.  Btw, I should add a new section in credits for you two 😉

**Comment by Aga-C** [comment]
Now, I've also noticed that the section name is "Others" - shouldn't it be "Other"? "Others" is referring to people.

**Comment by sunilpaulmathew** [comment]
> Others" is referr

Thanks again & sorry for my ignorance again :)

**Comment by Valdnet** [comment]
@sunilpaulmathew It looks so much better now 👍.
I would only change the line thickness under the settings titles. It's a bit too fat. It's too conspicuous. Set the thickness to the same as it is for the line, e.g. in the "All" window 😉.

**Comment by Valdnet** [comment]
Remember to reduce the line thickness to 1px in the application menu 😉.

**Comment by sunilpaulmathew** [comment]
@Valdnet 
If I forgot after the vacation, please please remind me again :)

**Comment by Valdnet** [comment]
> Remember to reduce the line thickness to 1px in the application menu

@sunilpaulmathew And how, are you working on this issue?

BTW: If you had a moment, please help me translate this [Simply Translate Mobile](https://github.com/ManeraKai/simplytranslate_mobile) application into your mother tongue and into the languages you know. 
Details for [translation](https://github.com/ManeraKai/simplytranslate_mobile#translation).
Thanks.
