### ISSUE TITLE
Remove exclamation marks

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#57]
Proposes to remove exclamation marks in all text strings. The application should not "scream". This may, in some situations, "scare" the user or discourage use.

**Comment by sunilpaulmathew** [comment]
@Valdnet 
I can, but it might take a long time to apply the same for other translations. Btw, is it really "**scary**"?

**Comment by Valdnet** [comment]
> Btw, is it really "scary"?

Exclamation marks are not used in applications. Only in exceptional circumstances, but really exceptional.

> I can, but it might take a long time to apply the same for other translations.

The translators can handle it 😉. And surely @Aga-C will deal with it quickly 😁.

**Comment by sunilpaulmathew** [comment]
> The translators can handle it 😉. And surely @Aga-C will deal with it quickly 😁.

There are few more people actively involved in translations. I think I'm giving them a lot of headaches. Will do it after my vacation :)

**Comment by sunilpaulmathew** [comment]
@Valdnet @Aga-C 
I'm back, but a bit tired after restless travel in Italy. I'll hopefully restart working in this weekend. How are you?

**Comment by Aga-C** [comment]
👍

**Comment by Valdnet** [comment]
@sunilpaulmathew Hi again :wave:. A bit of work testing another application 😁.

**Comment by sunilpaulmathew** [comment]
@Valdnet Exclamation marks are completely removed. I hope the users won't scare anymore :)
![Screenshot_1632720582](https://user-images.githubusercontent.com/15515387/134850104-cc74cde1-93eb-4846-b103-939e15f48847.png)

**Comment by Valdnet** [comment]
Cool. It gets better right away. Now the application is more user-friendly 😁.

**Comment by sunilpaulmathew** [comment]
> Cool 👍. It gets better right away. Now the application is more user-friendly 😁.
> 
> Now we are waiting for a new translation made by @Aga-C.

Ohh, I again forgot to upload original strings in POEditor. Will do in the evening so that @Aga-C and other people have a look.
