### ISSUE TITLE
Add search and sorting options in Exported Apps

### ISSUE THREAD

**Issue by Aga-C** [SmartPack/PackageManager#60]
Hi,

As you have more and more applications exported, it becomes harder to find the one you are looking for. Because of that, it would be useful to add search and sorting options as it is in the main app view (of course with proper adjustments).

**Comment by sunilpaulmathew** [comment]
@Aga-C 
Already addressed this issue. So, closing. if you find its not enough after the next release, please feel free to re-open it.

**Comment by Aga-C** [comment]
@sunilpaulmathew The search placeholder is missing. And I don't know the logic of how the sorting works. I can see Reverse Order option, but it's hard to tell what will be the result of it, when I don't know by what the list is sorted. Check following screenshots, I can't figure out what's the sorting here:

![image](https://user-images.githubusercontent.com/85929121/134823434-7d7c920c-d7d6-4e9a-8571-159d794e101b.png)

![image](https://user-images.githubusercontent.com/85929121/134823444-241f5a3c-77c5-48be-ac94-da1055a4bbe1.png)

**Comment by sunilpaulmathew** [comment]
@Aga-C 
There will be some small issues in sorting. Actually, the app considers the file name (not the app name or package name) of the exported app. I assumed that you saved some of them with package id (before I added a switch to change it) and then with real app names. I know its a little confusing, but I am convinced it is the best way. That's why I avoided using the term "Name" anywhere.

**Comment by Aga-C** [comment]
@sunilpaulmathew I've updated to the newest version. Thanks for the search option - it was the most important feature for me. 
I encountered that the exported apps are sorted alphabetically first by name, then by package name, what is fine. However, I still do not see a logic after selecting Reverse Order - it looks like it's completely random order. Also, Reverse Order is linked to the Reverse Order on the main screen (selecting it on the main screen or in the exported app affects both screens).

**Comment by Aga-C** [comment]
They shouldn't be connected to each other, for me it's a separate case.

**Comment by sunilpaulmathew** [comment]
> onnected to each

Will be done before the next release.

**Comment by Aga-C** [comment]
> What kind of files?

Similarly, as I can add an image, I'd like to add e.g. an audio recording or a video.

> I'm also planning to add an option to customize font size (or even fonts, if it doesn't bloat the app).

I thought about options while editing a note like bold, italic or changing font size.
