### ISSUE TITLE
[Enhancement] shizuku support

### ISSUE THREAD

**Issue by Efreak** [SmartPack/PackageManager#61]
Shizuku allows easily [un]installing apps and using system apis without root. More information [here](https://shizuku.rikka.app/introduction.html). This would allow queuing installs/uninstalls to be run without user interaction.

**Comment by sunilpaulmathew** [comment]
@Efreak Thanks, and I'll have a look (and reach a decision) on it later. I'll leave this issue open until then.

**Comment by sunilpaulmathew** [comment]
@Efreak 
Closing this commit as it already addressed in cbdad1fad18be834a6c79f2f07f374ac39c3d1da
