### ISSUE TITLE
Batch Export Not Working

### ISSUE THREAD

**Issue by HonestAbe7** [SmartPack/PackageManager#67]
I noticed if I select 2 apps and try to batch export, nothing shows up in my main storage; no package_manager directory. But if I do it manually, it works. I noticed you updated the Google Play version but wasn't sure of this was addressed here for the F-Droid version.

**Comment by sunilpaulmathew** [comment]
> I noticed if I select 2 apps and try to batch export, nothing shows up in my main storage; no package_manager directory. But if I do it manually, it works. I noticed you updated the Google Play version but wasn't sure of this was addressed here for the F-Droid version.

I just checked and find it's working. I need more details. Do you see a new page is opened and showing the details (such as "Exporting ...")? What do you mean by "do it manually"?
A possibility is, if you are on Android 9 + and do not grant "All Files Permission", the export path will be redirected to /sdcard/Android/data/com.smartpack.packagemanager/files

**Comment by HonestAbe7** [comment]
I meant manually by exporting one app at a time. I just tried to batch export 2 split APKs and still nothing showed up. I selected the 2 apps, hit batch on the bottom, it says it is done but no package_manager folder made. Is this a bug with 2 split APK files? Let me know if you would like the names of the apps to test this issue.

Nov 18, 2021 3:15:12 AM sp ***@***.***>:

**Comment by HonestAbe7** [comment]
Here are the links to the 2 apps I was trying to export in a batch. I don't know why, but if I export a lot at a time it does work.

1) https://play.google.com/store/apps/details?id=com.ihgyug.arcadium
Arcadium

2) https://play.google.com/store/apps/details?id=com.spicags.fill.one.line
Fill One Line

I gave you the links to these games so you can try it and see it really doesn't work for just these 2 apps.

Hope this helps!

Nov 18, 2021 11:43:34 AM Brent Barnhill ***@***.***>:

**Comment by sunilpaulmathew** [comment]
Actually, exporting (alone or batch/ APK or Split APKs) are working fine in my phone as well as in emulators. I really don't know what is happening here. One last question? Are you rooted or non-rooted? Thanks

**Comment by HonestAbe7** [comment]
I am non-rooted. I haven't tested out the updated Google Play version yet if this makes a difference?

Nov 19, 2021 2:00:02 AM sp ***@***.***>:

**Comment by sunilpaulmathew** [comment]
@HonestAbe7 
Latest Google Play version may not make any difference as it is published days before you raising this issue (unless some magical remedies).

**Comment by HonestAbe7** [comment]
OK. Just updated the F-Droid version so should be the same version on the Google play store. I just wanted to point this minor issue out on my end. You may close this thread. Thanks for looking into this. I value your time and energy looking into this.

Nov 19, 2021 3:38:39 AM sp ***@***.***>:

**Comment by HonestAbe7** [comment]
The new updated version is not able to export at all no matter what I do. I will be reverting to the previous version until this is fixed.

**Comment by sunilpaulmathew** [comment]
> The new updated version is not able to export at all. I just tried the previous 2 versions as well and I don't see any package manager directory when I export. I suspect it is the recent Google security update I just did on my phone? I have a cheap LG L355DL running Android 10 if this helps.

Can you tell me the exact version name you're using? If it is not v5.8, please update to it. If the issue still persist even after updating to v5.8, please send me a proper logcat. Otherwise,  I'm really helpless to fix the issue as I'm unable to reproduce it here. Also, just to mention, I'm also using an Android 10 device for development & testing of this a[pp.

**Comment by HonestAbe7** [comment]
What is a logcat and how do I use it?
