### ISSUE TITLE
v5.6 Installer Doesn't Initiate A Permission Dialogue

### ISSUE THREAD

**Issue by xyzcm** [SmartPack/PackageManager#68]
Hi! I hope I've successfully uploaded the screen record,  just in case, I'll still state my situation.

From fresh install, v5.6 doesn't have the "grant permission" when pressing the install option. It just goes back to default home UI.

But if you're from v5.5 and updated to v5.6, everything's fine.

Thank you!

**Comment by sunilpaulmathew** [comment]
> Hi! I hope I've successfully uploaded the screen record, just in case, I'll still state my situation.
> 
> From fresh install, v5.6 doesn't have the "grant permission" when pressing the install option. It just goes back to default home UI.
> 
> But if you're from v5.5 and updated to v5.6, everything's fine.
> 
> Thank you!

Screen record is missing. But, I managed to reproduce the issue. I'll try to fix it as soon as possible. Thanks for reporting this.
