### ISSUE TITLE
Unable to use installer on unrooted phone

### ISSUE THREAD

**Issue by myuseraccount** [SmartPack/PackageManager#69]
I have an un-rooted Samsung phone.  When I tap the + to select a package to install, it just goes back to the application list, without opening a file picker.  Does this feature require root?  It doesn't give me any kind of error message or crash the app.

**Comment by sunilpaulmathew** [comment]
@myuseraccount 
This issue was already reported (#68) and resolved as of v5.8. I'm sure that you're on an old version. Unfortunately, v5.8 (latest version) is not yet live on F-Droid.
Thanks

**Comment by xandro0777** [comment]
v6.0 is in F-droid now, could you test again?

**Comment by myuseraccount** [comment]
Works great!  I think it was fixed when I got v5.8 through F-Droid, as you mentioned.
