### ISSUE TITLE
"Cancel" button after executing "Export"

### ISSUE THREAD

**Issue by Valdnet** [SmartPack/PackageManager#70]
Steps:

1. Select the application.
2. Select "Export" from "Batch Options".

The "Cancel" button in "Batch Processing Completed" should be renamed to "Close". Currently, its text string is confusing for a user who thinks it will cancel the job.

![obraz](https://user-images.githubusercontent.com/47037905/144290449-9825e1e5-e211-457d-b457-5b46bc810701.png)

App:
Package Manager v5.6

**Comment by sunilpaulmathew** [comment]
@Valdnet
I value your suggestion. However, as I remember, that button will be visible only after the exporting job was completed. So, is it really confusing?

**Comment by Valdnet** [comment]
> However, as I remember, that button will be visible only after the exporting job was completed.

Exactly, but the user may not know it 😉.

> So, is it really confusing?

This is confusing to the user. Each time I wonder what he is canceling 😁.

**Comment by sunilpaulmathew** [comment]
I'll change it to close, back or exit. Don't know how many places it is currently using.

**Comment by Aga-C** [comment]
@sunilpaulmathew Could you update common strings for Polish, and also add the new Close string to POEditor for translation?

**Comment by sunilpaulmathew** [comment]
> e common strings for

Sorry, I missed your updates on common library. Also, Close is added to PM POEditor page. Thank you.
