### ISSUE TITLE
Q&A  How to Export to PC 

### ISSUE THREAD

**Issue by Pantyhose-X** [SmartPack/PackageManager#73]
My phone doesn't have enough storage, I have 600 apps, how to export directly to PC?  [webdav server](https://github.com/hacdias/webdav)、[ftp server](https://github.com/ppareit/swiftp)、ubs data cable ?

**Comment by sunilpaulmathew** [comment]
@Pantyhose-X 
Although it is a good suggestion, it looks like too difficult in modern devices due to Google's newly introduced restrictions (User app's can't really access to most of the storage spaces).

**Comment by Pantyhose-X** [comment]
> @Pantyhose-X Although it is a good suggestion, it looks like too difficult in modern devices due to Google's newly introduced restrictions (User app's can't really access to most of the storage spaces).

hey bro 
export to [WebDAV](https://en.wikipedia.org/wiki/WebDAV), may be the only way to solve this problem.
PC run WebDAV server, Android Mount server
