### ISSUE TITLE
FEATURE REQUEST: Include versionName and versionCode in file name.

### ISSUE THREAD

**Issue by ladar** [SmartPack/PackageManager#77]
I like dumping the packages off a device, and it's nice if the file name includes the versionName/Code so updates don't overwrite existing files (yet identical versions stay the same).

Adding the ability to name exported files `packageId-versionName-versionCode.apk` (or apkm) would be ideal.

Also, I've noticed I need to manually grant file system access to the app before exports work. Otherwise the app appears to work, but doesn't, which is frustrating.

**Comment by sunilpaulmathew** [comment]
@ladar 
Thanks for raising this issue. I'll work on the (first) suggestion soon.

Regarding the second part, can you tell me some more details about reproducing the issue. Also, are you installed this app from google Play or F-Droid (Both has some differences related to the permission side)?

**Comment by ladar** [comment]
@sunilpaulmathew thank you for adding the name convention. 

As for the second issue, I made a short video. As you can see, my first export attempt **appeared** to work just fine, but nothing was actually saved. If a user went looking for the `Package_Manager` directory, it wouldn't be there, and I personally found this very confusing. 

So I was just saying, an export operation should error/and or tell the user they need to grant the Files permission, rather than appearing to work, when it isn't.

It seems on this device (Pixel 6 w Android 12), going to Exported Apps via the menu does show that you need to grant File system access. In theory it should show this request before attepting an export (if the permission is lacking).

https://user-images.githubusercontent.com/1434008/163776831-cdda83b3-aa67-4d7e-a88d-d36ad629c90c.mp4

**Comment by sunilpaulmathew** [comment]
@ladar 
Thanks a lot.  I completely understand it. I'll fix it soon.
Have a nice day

**Comment by ladar** [comment]
@sunilpaulmathew thank you. I'll keep an eye out and test when it hits F-Droid.
