### ISSUE TITLE
Location of Uninstalled Apps?

### ISSUE THREAD

**Issue by kjadfksjd** [SmartPack/PackageManager#85]
Hey,
I've uninstalled some apps. Now my phone doesn't boot into ROM. Where are the uninstalled apps located? I want to "install" it again. Can you help me finding directions?

**Comment by sunilpaulmathew** [comment]
@kjadfksjd 
Unfortunately, app won't store uninstalled apps. You can however restore it via adb (if connection possible & you know the package names).

**Comment by kjadfksjd** [comment]
Thank you. I will just wipe everything and be more careful from now on :)
