### ISSUE TITLE
In batch mode, the operation results page does not seem to scroll automatically.

### ISSUE THREAD

**Issue by marsgovernor** [SmartPack/PackageManager#9]
When many APPs are disabled at once, it does not seem to scroll automatically.

Another suggestion:
When an app is disabled, it is expected to return to the current scrolling position of the main page instead of the top position.

**Comment by sunilpaulmathew** [comment]
> ected to return to the current scrolling posit

Thanks for reporting the first issue, which I will fix (hopefully) in next update. You'll probably notice that issue on various batch tasks as well as with Split APK installation.

Regarding the the suggestion, currently it is done (refreshing page that led to the mentioned effect) intentionally to get the new status in effect (after disabled/enabled/uninstalled etc.). I'll have some other idea to likely deal with it. However, I'm not fully sure it will work efficiently. Anyway, I'll certainly try.

**Comment by sunilpaulmathew** [comment]
@marsgovernor 
Scrolling issue should be fixed in v3.6 (submitted to google play). Other suggestions are still in pending.

**Comment by marsgovernor** [comment]
Thank you for your hard work!
